#!/usr/bin/env python3
"""Start Harbour and retire bootstrap credentials only after a durable receipt."""
import fcntl
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
BOOTSTRAP_KEYS = {"HARBOUR_ADMIN", "HARBOUR_ADMIN_PASSWORD_HASH", "HARBOUR_BOOTSTRAP_ID", "HARBOUR_PASSWORD"}


def read_env(path):
    if not stat.S_ISREG(path.lstat().st_mode):
        raise RuntimeError(".env must be a regular file, not a symlink.")
    os.chmod(path, 0o600)
    text = path.read_text()
    values = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.fullmatch(r"([A-Z][A-Z0-9_]*)=([^\s'\"$`\\#]*)", line)
        if not match or match[1] in values:
            raise RuntimeError("Managed .env needs unique KEY=value lines with unquoted literal values, as generated by setup_env.py.")
        values[match[1]] = match[2]
    if values.get("FIRST_RUN", "").lower() not in ("true", "false"):
        raise RuntimeError("Set FIRST_RUN=True for initial setup, or False for an existing database.")
    return text, values


def cleaned_env(text):
    lines = []
    for line in text.splitlines():
        key = line.split("=", 1)[0].strip()
        if key in BOOTSTRAP_KEYS:
            continue
        lines.append("FIRST_RUN=False" if key == "FIRST_RUN" else line)
    return "\n".join(lines) + "\n"


def retire_credentials(path, expected):
    if path.is_symlink() or path.read_text() != expected:
        raise RuntimeError(".env changed during startup. Credentials were left untouched; rerun after checking the file.")
    fd, temporary = tempfile.mkstemp(prefix=".env.cleanup-", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as output:
            output.write(cleaned_env(expected))
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
        directory = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def compose(*args, capture=False):
    # Shell exports must not silently override the file we are about to clean.
    env = {k: v for k, v in os.environ.items() if not k.startswith(("HARBOUR_", "COMPOSE_")) and k != "FIRST_RUN"}
    result = subprocess.run(["docker", "compose", "--project-directory", str(ROOT), "--env-file", str(ROOT / ".env"), *args],
                            cwd=ROOT, env=env, check=True, text=True, stdout=subprocess.PIPE if capture else None,
                            timeout=60 if capture else 1800)
    return result.stdout if capture else None


def start():
    path = ROOT / ".env"
    original, values = read_env(path)
    first_run = values["FIRST_RUN"].lower() == "true"
    if first_run and not all(values.get(k) for k in BOOTSTRAP_KEYS - {"HARBOUR_PASSWORD"}):
        raise RuntimeError("First-run fields are incomplete. Use scripts/setup_env.py for a new installation.")
    print("Building and starting Harbour…", flush=True)
    compose("up", "-d", "--build", "--wait", "--wait-timeout", "120")
    if first_run:
        receipt = json.loads(compose("exec", "-T", "harbour", "python", "-m", "harbour.bootstrap", capture=True))
        if not (receipt.get("seeded") and receipt.get("id") == values["HARBOUR_BOOTSTRAP_ID"]
                and receipt.get("name") == values["HARBOUR_ADMIN"]):
            raise RuntimeError("The running database did not confirm this bootstrap account. .env was not changed. An existing database will never be reseeded.")
        retire_credentials(path, original)
        print("Admin creation verified. Bootstrap credentials removed; FIRST_RUN=False. Clearing the container environment…", flush=True)
        compose("up", "-d", "--no-build", "--force-recreate", "--wait", "--wait-timeout", "120")
    result = json.loads(compose("exec", "-T", "harbour", "python", "-m", "harbour.bootstrap", "--check-clean", capture=True))
    if not result.get("clean"):
        raise RuntimeError("Bootstrap environment is not clean. Check .env and rerun this script.")
    print("Harbour is healthy. Open " + values.get("HARBOUR_ORIGIN", "your configured origin") + ".")
    print("FIRST_RUN=False is set. Keep .env / HARBOUR_SECRET and the data volume backed up securely.")


def main():
    # Coordinate setup runs without giving the web container access to host files.
    fd = os.open(ROOT / ".env.setup.lock", os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "w") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            raise RuntimeError("Another Harbour startup is in progress.") from None
        start()


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, OSError, ValueError, subprocess.SubprocessError, KeyboardInterrupt) as error:
        print("Startup stopped:", str(error) or "cancelled", file=sys.stderr)
        print("Fix the problem and rerun scripts/start.py. Existing accounts and HARBOUR_SECRET are preserved.", file=sys.stderr)
        sys.exit(1)
